// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmyVsUIAcDFPDAjrn1pj4s_b17JkAuEaY',
    appId: '1:254097529461:web:43732811c5177dc50df63c',
    messagingSenderId: '254097529461',
    projectId: 'invoiceease-303c7',
    authDomain: 'invoiceease-303c7.firebaseapp.com',
    storageBucket: 'invoiceease-303c7.appspot.com',
    measurementId: 'G-WXEB6YG6GF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpCx-DJs8-7UPdqGi17ABVnzRx9jNVET0',
    appId: '1:254097529461:android:4da36df4a2075e620df63c',
    messagingSenderId: '254097529461',
    projectId: 'invoiceease-303c7',
    storageBucket: 'invoiceease-303c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgI481dwTdpPtsfanyp4eiTd7wet72XYg',
    appId: '1:254097529461:ios:a57073981be074720df63c',
    messagingSenderId: '254097529461',
    projectId: 'invoiceease-303c7',
    storageBucket: 'invoiceease-303c7.appspot.com',
    iosBundleId: 'com.example.invoiceease',
  );
}
